### ISSUE TITLE
libsass/sassutils 0.15.0 breaks setuptools sdist

### ISSUE THREAD

**Issue by moser** [sass/libsass-python#266]
Hi,
starting with version 0.15.0, sassutils seems to break something about `python setup.py sdist`:

```
$ python setup.py sdist
running build_sass
building 'XXX' sass
running sdist
running egg_info
[...]
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    entry_points={"console_scripts": ["foo=pkg.mod:main"]},
  File "/usr/local/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/sdist.py", line 48, in run
    self.check_readme()
  File "/usr/local/lib/python3.5/site-packages/sassutils/distutils.py", line 200, in check_readme
    self.filelist.extend(join(*pair) for pair in files)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 482, in extend
    self.files.extend(filter(self._safe_path, paths))
  File "/usr/local/lib/python3.5/site-packages/sassutils/distutils.py", line 200, in <genexpr>
    self.filelist.extend(join(*pair) for pair in files)
  File "/usr/local/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
```

Package version

```
pip: 18.0
wheel: 0.31.1
setuptools: 40.4.3
```

setup.py

```
from setuptools import setup, find_packages
import os

def read_requirements():
    res = []
    with open(os.path.join(os.path.dirname(__file__), "requirements.txt")) as fp:
        for line in fp:
            if not line.startswith("#") or not line:
                res.append(line)
    return res

setup(
    name="Project",
    version="0.1",
    long_description="",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=read_requirements(),
    setup_requires=["libsass >= 0.14.5"],
    sass_manifests={"XXX": ("static/sass", "static/css", "/static/css")},
    entry_points={"console_scripts": ["foo=pkg.mod:main"]},
)
```

**Comment by asottile** [comment]
Can you confirm that #267 fixes this for you?

**Comment by asottile** [comment]
0.15.1 has a fix for this -- thanks for the report!

**Comment by moser** [comment]
Thanks! :-)
