### ISSUE TITLE
from sassutils.wsgi import SassMiddleware failure

### ISSUE THREAD

**Issue by kshaeffer** [sass/libsass-python#281]
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask import Flask
>>> from sassutils.wsgi import SassMiddleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sassutils/wsgi.py", line 14, in <module>
    from sass import CompileError
  File "/usr/lib/python3/dist-packages/sass.py", line 27, in <module>
    import _sass
ImportError: /usr/lib/python3/dist-packages/_sass.cpython-36m-x86_64-linux-gnu.so: undefined symbol: sass_option_push_import_extension

I'm on Ubuntu 18.10:

apt-get install python3-libsass
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libsass1
The following NEW packages will be installed:
  libsass1 python3-libsass
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 797 kB of archives.
After this operation, 2,900 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic/universe amd64 libsass1 amd64 3.5.4+20180621~c0a6cf3-1 [764 kB]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu cosmic/universe amd64 python3-libsass amd64 0.14.5-1 [33.0 kB]
Fetched 797 kB in 0s (4,509 kB/s)         
Selecting previously unselected package libsass1:amd64.
(Reading database ... 178761 files and directories currently installed.)
Preparing to unpack .../libsass1_3.5.4+20180621~c0a6cf3-1_amd64.deb ...
Unpacking libsass1:amd64 (3.5.4+20180621~c0a6cf3-1) ...
Selecting previously unselected package python3-libsass.
Preparing to unpack .../python3-libsass_0.14.5-1_amd64.deb ...
Unpacking python3-libsass (0.14.5-1) ...
Setting up libsass1:amd64 (3.5.4+20180621~c0a6cf3-1) ...
Processing triggers for libc-bin (2.28-0ubuntu1) ...
Setting up python3-libsass (0.14.5-1) ...
root@ip-10-109-202-148:~# dpkg -L python3-libsass
/.
/usr
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/_sass.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/_sass.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/libsass-0.14.5.egg-info
/usr/lib/python3/dist-packages/libsass-0.14.5.egg-info/PKG-INFO
/usr/lib/python3/dist-packages/libsass-0.14.5.egg-info/dependency_links.txt
/usr/lib/python3/dist-packages/libsass-0.14.5.egg-info/entry_points.txt
/usr/lib/python3/dist-packages/libsass-0.14.5.egg-info/requires.txt
/usr/lib/python3/dist-packages/libsass-0.14.5.egg-info/top_level.txt
/usr/lib/python3/dist-packages/sass.py
/usr/lib/python3/dist-packages/sassc.py
/usr/lib/python3/dist-packages/sasstests.py
/usr/lib/python3/dist-packages/sassutils
/usr/lib/python3/dist-packages/sassutils/__init__.py
/usr/lib/python3/dist-packages/sassutils/builder.py
/usr/lib/python3/dist-packages/sassutils/distutils.py
/usr/lib/python3/dist-packages/sassutils/wsgi.py
/usr/share
/usr/share/doc
/usr/share/doc/python3-libsass
/usr/share/doc/python3-libsass/changelog.Debian.gz
/usr/share/doc/python3-libsass/copyright

**Comment by QuLogic** [comment]
> @asottile added the upstream-bug label an hour ago

Technically a downstream bug, no?

**Comment by asottile** [comment]
> > @asottile added the upstream-bug label an hour ago
> 
> Technically a downstream bug, no?

Close enough, I'm not making a label from my phone :laughing:
