### ISSUE TITLE
Install Error "UnicodeDecodeError"

### ISSUE THREAD

**Issue by RocsSun** [sass/libsass-python#292]
Hey, man!
When I use pip to install `libsass-python`, throw a decoding exception, can you help me solve it, and thank you!
```dos
Microsoft Windows [版本 10.0.17763.316]
(c) 2018 Microsoft Corporation。保留所有权利。

(Django-1.11.15venv) F:\Project\DjangoPro\YoutobeBlog>pip install libsass django-compressor django-sass-processor
Collecting libsass
  Using cached https://files.pythonhosted.org/packages/c4/a6/6c6b744878e57934a3e9517128e77999c32126cb37b5c53f2da3b1227b6d/
libsass-0.17.0-cp36-cp36m-win_amd64.whl
Collecting django-compressor
  Using cached https://files.pythonhosted.org/packages/02/7b/deb4605f95bcefb9760ff130533553230a1c25f4d383ed0735b075d71b29/
django_compressor-2.2-py2.py3-none-any.whl
Collecting django-sass-processor
  Using cached https://files.pythonhosted.org/packages/93/2d/0f50d7414d59131e5365a869c1092996ad3c6b112b6409f5c80576cae101/
django-sass-processor-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Linga\AppData\Local\Temp\pip-install-biiqjcao\django-sass-processor\setup.py", line 9, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 3271: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Linga\AppData\Local\Temp\pip-install-biiqjcao\djan
go-sass-processor\
```

**Comment by asottile** [comment]
That error is from installing `django-sass-processor` and not our package, please open an issue there

**Comment by RocsSun** [comment]
> That error is from installing `django-sass-processor` and not our package, please open an issue there

OMG!Thanks!

**Comment by asottile** [comment]
No problem!  Good luck tracking it down :)

**Comment by asdbaihu** [comment]
how to solver

**Comment by asottile** [comment]
@asdbaihu the issue in the original post was with a different package entirely -- can you paste your output?
