### ISSUE TITLE
python2.7 windows wheels failed to build for 0.19.0

### ISSUE THREAD

**Issue by asottile** [sass/libsass-python#296]
I'll have to figure out a way to fix that

Here's the error:

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing d:\a\1\s
ERROR: Exception:
Traceback (most recent call last):
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\commands\wheel.py", line 164, in run
    resolver.resolve(requirement_set)
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\operations\prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\download.py", line 873, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "d:\a\1\s\.tox\py27\lib\site-packages\pip\_internal\download.py", line 778, in unpack_file_url
    shutil.copytree(link_path, location, symlinks=True)
  File "c:\hostedtoolcache\windows\python\2.7.14\x86\Lib\shutil.py", line 222, in copytree
    raise Error, errors
Error: [('D:\\a\\1\\s\\libsass\\test\\e2e\\unicode-pwd\\Sa\xb4ss-UT\xb8F8', 'c:\\users\\vssadm~1\\appdata\\local\\temp\\pip-req-build-e7ok_o\\libsass\\test\\e2e\\unicode-pwd\\Sa\xb4ss-UT\xb8F8', "[Errno 2] No such file or directory: 'D:\\\\a\\\\1\\\\s\\\\libsass\\\\test\\\\e2e\\\\unicode-pwd\\\\Sa\\xb4ss-UT\\xb8F8'"), ('D:\\a\\1\\s\\libsass\\test\\e2e\\unicode-pwd\\S\xe1ss-UTF8', 'c:\\users\\vssadm~1\\appdata\\local\\temp\\pip-req-build-e7ok_o\\libsass\\test\\e2e\\unicode-pwd\\S\xe1ss-UTF8', "[Errno 2] No such file or directory: 'D:\\\\a\\\\1\\\\s\\\\libsass\\\\test\\\\e2e\\\\unicode-pwd\\\\S\\xe1ss-UTF8'")]
##[error]Bash exited with code '2'.
```

**Comment by nschonni** [comment]
Can you use the root .gitignore to mask them out of the submodule cloning?

**Comment by asottile** [comment]
@nschonni 🤔 could you provide an example? I'm not sure I've heard of anything like that

**Comment by nschonni** [comment]
Was just thinking of adding the line `libsass/test/e2e/unicode-pwd/` to https://github.com/sass/libsass-python/blob/master/.gitignore
Maybe i'm misunderstanding what is getting stuck, and it needs to be excluded from the python packaging setup instead

**Comment by nschonni** [comment]
Think libsass also had issues with this on windows, so maybe it is catching something it should https://github.com/sass/libsass/blob/master/appveyor.yml#L83

**Comment by asottile** [comment]
oh for sure, this is tickling a bug in python2.7 on windows -- unfortunately the bug isn't something I can patch because it's in the packaging / stdlib bits

I might workaround by just deleting that directory for the windows py27 builds
