### ISSUE TITLE
libsass-python relies on removed distutils.msvc9compiler module

### ISSUE THREAD

**Issue by martin-vi** [sass/libsass-python#468]
Windows build fails with:

```
> pip show setuptools
Name: setuptools
Version: 74.1.1
[…]
>pip install libsass --no-binary :all:
Looking in indexes: https://[…]/simple
Collecting libsass
  Downloading https://[…]/libsass-0.23.0.tar.gz (316 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-pncoj2ti\libsass_a342bf2167704962b7f31ad07daa61f2\setup.py", line 100, in <module>
          from distutils.msvc9compiler import get_build_version
      ModuleNotFoundError: No module named 'distutils.msvc9compiler'
      [end of output]
[…]
```

See also https://github.com/python-cffi/cffi/issues/117. A possible workaround for now is to use an older setuptools version, e.g. `setuptools<74`.

**Comment by eipiriru** [comment]
how to solve that?

**Comment by asottile** [comment]
#472
